version: 2
updates:
  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: "weekly"
      day: "tuesday"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels:
      - dependencies
      - go
      - "Changed"
    groups:
      global:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directories: ["/", ".github/actions/*"]
    schedule:
      interval: "weekly"
      day: "tuesday"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels:
      - dependencies
      - github_actions
      - "Changed"
