name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * 0'

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package:
    uses: SIGTERM-Labs/actions/.github/workflows/docker-build.yaml@main
    with:
      alternate-latest-mode: true
